### ISSUE TITLE
Display just the Client Ticket

### ISSUE THREAD

**Issue by Michael-Reich** [responsiv/support-plugin#1]
Is it possible just to show the ticket for the client not all tickets on the listing?

**Comment by daftspunk** [comment]
Not sure what you mean, is it front-end or back-end?

**Comment by Michael-Reich** [comment]
If a user login and clicks on tickets, that he just sees his created ones. Not all tickets.

**Comment by daftspunk** [comment]
I recall this was a bug many moons ago. What version of this plugin are you using?
