### ISSUE TITLE
Missage cannot be found

### ISSUE THREAD

**Issue by Nikl10** [responsiv/support-plugin#3]
when i replying from-  localhost/backend/responsiv/ support/preview/4 
I see that the respons by Admin is successfully send but when i open- localhost/ ticket-message
I see - Missage cannot be found. In my SQL the replying messages i have. 
WHAT HAVE I DO NEXT ???

NOTE i don't found a video support about how to install your plagin.  Your plagin cost 100$. 
I think best one  time to see then 100  to hear. ](url)

**Comment by Nikl10** [comment]
Thanks i did it all work fine

**Comment by daftspunk** [comment]
We'll work on a screencast for setting this up soon. Thanks!
