### ISSUE TITLE
Display Submit Form

### ISSUE THREAD

**Issue by Thuthu001** [responsiv/support-plugin#6]
I added the component on my page. However, only one field (Ticket type) is displayed on the screen. What must I have done wrong? Attached is the screenshot of the form.

![ticket](https://user-images.githubusercontent.com/45457127/49221683-7a9bf600-f3e2-11e8-9ad1-fa6a0f4ab152.png)

I used the example on the documentation (OctoberCMS page)to attach the component.

**Comment by daftspunk** [comment]
Make sure you have the AJAX framework loaded, once an item is selected the form should appear
