### ISSUE TITLE
Failed to update composer dependencies 

### ISSUE THREAD

**Issue by webBook-cz** [responsiv/support-plugin#8]
Fresh install of October 3.1.14

Only possible installation was with parameter --want=dev-master (but this is common problem of October 3.1, not specific for the plugin). But plugin was disabled by system: cannot find composer dependencies 

Exception: Failed to update composer dependencies in /home/tickets/public_html/vendor/october/rain/src/Composer/Manager.php:73
Stack trace:
`#0 /home/tickets/public_html/modules/system/console/PluginInstall.php(75): October\Rain\Composer\Manager->require()`
`#1 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): System\Console\PluginInstall->handle()`
`#2 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()`
`#3 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()`
`#4 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()`
`#5 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()`
`#6 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\Container\Container->call()`
`#7 /home/tickets/public_html/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()`
`#8 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\Component\Console\Command\Command->run()`
`#9 /home/tickets/public_html/vendor/symfony/console/Application.php(1002): Illuminate\Console\Command->run()`
`#10 /home/tickets/public_html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()`
`#11 /home/tickets/public_html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()`
`#12 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()`
`#13 /home/tickets/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()`
`#14 /home/tickets/public_html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()`
`#15 {main}`

**Comment by daftspunk** [comment]
Hi, 

There was a problem with the composer file for this plugin so it didn't pick up the version tag. It should be fixed now and the v1.0.13 should be available.

Thanks

**Comment by webBook-cz** [comment]
Thanks for quick solution. But anyway: manual installation of Rainlab.User dependency is still needed.

**Comment by daftspunk** [comment]
Thanks, we are working on a solution to install dependencies automatically. Should be available soon.
