### ISSUE TITLE
Can I manage the tickets by rainlab-user or just Octobers CMS admin?

### ISSUE THREAD

**Issue by frasjaf** [responsiv/support-plugin#9]
I need to manage the tickets by rainlab-user is that possible?

**Comment by daftspunk** [comment]
Hi @frasjaf 

The scope of this plugin is for administrators to manage tickets. Users can manage their own tickets, this could be extended to allow users to manage other user's tickets. The components are already there and just need to be modified, or you can extend the classes in your own plugin.

I hope this helps!
